### ISSUE TITLE
discussion about how to use with smartphones

### ISSUE THREAD

**Issue by molleweide** [vhyrro/neorg#11]
I'm starting a thread where we can talk about how could one use neorg on the go. How could one edit notes and stuff on ones smartphone and keep stuff in sync or in git repo?? How do other people do this?
I am personally quite new to neovim and have never dabbled in syncing stuff etc. but I would like to learn? What would be some recommendations on how to do this with neorg if neorg was my main note taking environment?

I am not sure if this is off topic but I think that it makes sense to think/talk about this since it falls in line with the overall philosphy of neorg. What do you think @vhyrro? Am I being stupid here??

**Comment by shadmansaleh** [comment]
If you're on android . You should try out [termux](https://github.com/termux/termux-app) . You wilk find latest version in [F-droid](https://f-droid.org/en/packages/com.termux)

Just install neovim and setup you're coniguration there . And you'll be golden . You can just use it as you'd use it from your PC .

As keyboard for terminal I do recomend [Hackers-keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)

**Comment by molleweide** [comment]
Hmm. Yeah i have heard good things about termux. Currently i am having an old iphone which is not so good for this 😞

**Comment by molleweide** [comment]
Also i’d close this but i am AFK currently

**Comment by vhyrro** [comment]
I think that syncing (like e.g. taskwarrior has) would be pretty cool, however I'm gonna be honest, that's faaar from where we are now. Neorg will get taskwarrior integration eventually (no determined version, it may come at any time), and so you could sync your TODO items with taskwarrior then. For now though I think we shouldn't worry ourselves too heavily with something like that tho :)

**Comment by molleweide** [comment]
Cool thanks for your input?

**Comment by vhyrro** [comment]
Ouch, I may have completely missed the point. Small brain. @shadmansaleh pretty much mentioned everything (I wouldn't have added anything special). Termux is the way to go for phones :)

**Comment by molleweide** [comment]
Haha no but termux is only for android. However, i just found out about ISH terminal for ios and taskwarrior ios. 

Maybe i will get android in future. Dunno yet

**Comment by akinsho** [comment]
This is definitely a very long term concern but FWIW, emacs has: https://github.com/orgzly/orgzly-android, which I only mention because maybe (*way*) down the line something like this could exist for neorg if the format was such that it was easy to serialize and deserialize.

**Comment by molleweide** [comment]
Cool it’s so much fun to read your replies since i am see myself only as a beginner

**Comment by kuznetsss** [comment]
I would really want to use neorg, but without smartphone application it's not so comfortable for me.
For Android it seems [Markor](https://github.com/gsantner/markor) looks like a good application to add neorg support.

**Comment by vhyrro** [comment]
Yeah that sounds like an interesting idea. Sadly it's not close on our todo list. I think someone else would have to maintain that, it would simply be a bit too much to manage an entire ecosystem in neovim and also another ecosystem outside of it. Users are completely free to incorporate the neorg format wherever they please so if anyone's down to try implementing Neorg in a mobile setting then be my guest! :)
