### ISSUE TITLE
Code blocks with @code ruby don't seem to work

### ISSUE THREAD

**Issue by metalelf0** [vhyrro/neorg#15]
Hi @vhyrro! Thanks a lot for this project, I'm really intrigued by it and I can't wait to see it grow!

I was trying out the code blocks syntax and it seems the following code doesn't highlight ruby as expected:

```
@code ruby
def my_method(something)
end
@end
```

Following https://github.com/vhyrro/neorg/issues/7, here I am reporting it :) Thanks again and keep up the great work!

**Comment by vhyrro** [comment]
Hmm, that's peculiar. It works on my end. Do you by any chance have the ruby treesitter parser installed? You should have it.

Also, sorry if I reply really late sometimes. I read the issues as soon as they arrive, but I can't respond to them instantly since I'm busy with other stuff.

**Comment by metalelf0** [comment]
Oh, damn. Shame on me. I must have uninstalled it unintentionally and
forgot to re-install it. `:TSInstall ruby` and it's working!

Thanks for your reply and don't worry, the delay is absolutely not a deal
:) Keep up the great work!

Il giorno mar 13 lug 2021 alle ore 16:32 vhyrro ***@***.***>
ha scritto:

**Comment by vhyrro** [comment]
Sick, glad to see that it works now :P
Thank you for the kind words!
