### ISSUE TITLE
docs: clarify if packer is required, or suggested, for installation

### ISSUE THREAD

**Issue by jmtd** [vhyrro/neorg#16]
This looks interesting but I'm still trying to grok the installation instructions. You list "Packer:" which to the uninitiated (me!) looks like one bundle manager amongst many (I currently use pathogen). It's not clear whether Packer is a hard requirement, or merely a suggestion, and it would be good to clarify that.

I don't see any clear indication as to which Neovim versions are supported, but Packer has >= 0.5.0 (which is newer than Debian have managed to package so far, for example), so if Packer is a hard requirement than that's a transitive minimum Neovim version for neorg, too.

**Comment by mrossinek** [comment]
FWIW you can easily put the configuration into a separate Lua code block. Be that in your `init.vim`, `init.lua` or any other file. This allows you to decouple the installation and configuration from each other.
Just as an example this is what I did: https://github.com/mrossinek/dotfiles/commit/b0930d122655d2fbdae30ae009bde3be71d1037b
Note, that I don't use a Vim package manager but the separate files should be self explanatory.

**Comment by vhyrro** [comment]
@jmtd I've addressed the problem in the README by letting users know that installation is possible via any plugin manager and that Neovim 0.5+ is required. Does that look alright to ya?

**Comment by syntezoid** [comment]
https://github.com/vhyrro/neorg/pull/20

**Comment by vhyrro** [comment]
Since there was no answer from jmtd I think we can say it's fine to close the issue now :)

**Comment by jmtd** [comment]
Thanks, I had this bookmarked to return to, I just hadn't got around to it yet. Looks good thank you!
