### ISSUE TITLE
Literate config files.

### ISSUE THREAD

**Issue by mkblast** [vhyrro/neorg#26]
So it is a simple question can we do a Literate config " _Literate programming_" my `init.lua` in `neorg` like `emacs` with `org-mode`.

That would be cool so I can organize my giant config file.

I'll be watching this project closely.

Also take my Stare.

Edite: Fix spelling.

**Comment by vhyrro** [comment]
Since literate programming isn't crazy difficult I'm thinking of quietly shoving it in before 0.1 releases :)
I'm thinking of just implementing just tangling, nothing crazy like executing code blocks and seeing their output in virtual text just yet

Also thanks for the stare :eyes:

**Comment by mkblast** [comment]
That cool.

So we can export it to a different file type with only the code blocks that's a really game changer so now I can really ditch emacs.

Thanks man.
