### ISSUE TITLE
Multiline insert of bulletpoint, changes icon only for the first one.

### ISSUE THREAD

**Issue by kishikaisei** [vhyrro/neorg#32]
When trying to add bullet point to multiple lines, only the first line gets the `Bull's eye` icon.
![neorg](https://user-images.githubusercontent.com/1894123/126899409-eb6964b7-d277-4817-8d50-6d8d6276fef1.gif)

**Comment by vhyrro** [comment]
Ah, I had a feeling this bug would appear in one way or another. This shouldn't be too much of a difficult fix thankfully, the issue is that the concealer only updates the current line after a change rather than the whole range. Imma get to work on that :)

**Comment by kishikaisei** [comment]
And the same thing happens when I have a list of bullet items, delete them, than undo the deletion, only the first line have the 'bull's eye' icon, all other lines have the asterisk.

**Comment by vhyrro** [comment]
![epic](https://user-images.githubusercontent.com/76052559/126904104-21ea0d75-a90d-4514-9338-5a27c0bc02db.png)
So far as you can see the bug fixes are going very smoothly and very well, 100% working

**Comment by vhyrro** [comment]
Alright, I've managed to fix this. I've tried soo many different methods, but none of them worked. The only solution is to reconceal the entire buffer every time a change happens. Thankfully it's not crazy taxing on the editor :)

Make sure to be using the unstable branch and see whether everything works. If it does then please close the issue else let me know of any other bugs!

**Comment by kishikaisei** [comment]
Chef's kiss to you, and I am always running unstable so I can help with at least bug reporting 😉
