### ISSUE TITLE
Code block colors

### ISSUE THREAD

**Issue by akinsho** [vhyrro/neorg#35]
![image](https://user-images.githubusercontent.com/22454918/127200504-168ff8c9-d761-4066-b812-aa84a6c9582f.png)

The color for code blocks seems to be hard coded to brown, which I think will not necessarily work for a lot of colorschemes. I think a simpler solution would be to link to a common highlight group but since it's not really clear what highlight group will necessarily be darker than the `Normal` background color, what I do in my plugins is use a function which darkens the hex value of the normal background, so it works for most colour schemes without depending on a potentially absent highlight group.

https://github.com/akinsho/nvim-bufferline.lua/blob/fec44821eededceadb9cc25bc610e5114510a364/lua/bufferline/colors.lua#L10-L33

I've also noted that the points after I insert a new line aren't highlighted, no idea why haven't looked into it at all, but just thought I'd mention.

**Comment by vhyrro** [comment]
Man, you saved the day. I wasn't a fan of my solution either and hoped that the extmark highlight blending would at least help a bit but that's not its behaviour. I'll look into this when i get home, thx man

Also, could you elaborate what you mean by points not highlighting? I don't think i quite get it lol

**Comment by akinsho** [comment]
Sorry should have been clearer, in the screenshot above every linebreak seems to be highlighted the same as the background colour, so it looks like there are holes in the code block highlighting. For example, just after the `lua` there is a single cell that is `blue` instead of the same colour as the code block background.

**Comment by vhyrro** [comment]
Ah i see it now, wow i didn't catch that lol

That's a problem, I'll look into that too

**Comment by vhyrro** [comment]
I made an initial test for the code blocks. I switched around a few things here and there and made the function dim the code blocks by default instead of making them brighter (by supplying negative percentages you can make it brighter if you so choose), I think it looks awesome! If you have any ideas or things you want to point out regarding the code then please do. Also I can't seem to replicate that last bug you're having, it works great on my end :thinking:

**Comment by vhyrro** [comment]
Oh and also I'm gonna change the way the highlight is initialized because customizing it is a pain rn haha

**Comment by akinsho** [comment]
@vhyrro just tried this out, and it looks much nicer in my colorscheme. I also tracked down the issue I was having to using `listchars` with `eol` set to an empty space rather than being `nil` this meant that the eol character was being coloured as `NonText` and so was overriding the highlight `neorg` was doing.

**Comment by vhyrro** [comment]
I see! That's interesting. Well good to know that stuff at least looks good :)

I don't know whether checking for listchars would be overkill in neorg, i might play around with it tho

**Comment by akinsho** [comment]
@vhyrro I think it's kind of a rare error, could easily imagine changing it being disruptive. If it comes up again, maybe a note in the docs or something 🤷🏿 I guess it's most interesting because it means a user's highlights can break through, but I think that's probably better than overriding things a user might not want overriden. In my case that highlight should not really have had a background colour but must have been set by my colorscheme.

Anyway will close this out since the main issue is resolved

**Comment by vhyrro** [comment]
I agree, leaving a note in the docs might be the best thing to do. The new dimming code is awesome, once again thx for the idea :)
