### ISSUE TITLE
Filetype for normal file(s) set to norg

### ISSUE THREAD

**Issue by akinsho** [vhyrro/neorg#39]
I've noticed that when I leave a neorg buffer sometimes the filetype of the buffer I was in before opening the neorg file is set to `norg`.

The way that I reproduce this is is using the following config
```lua
    use {
      'vhyrro/neorg',
      branch = 'unstable',
      requires = { 'vhyrro/neorg-telescope' },
      config = function()
        require('neorg').setup {
          load = {
            ['core.defaults'] = {},
            ['core.integrations.telescope'] = {},
            ['core.keybinds'] = {
              config = {
                default_keybinds = true,
                neorg_leader = '<Leader>o',
              },
            },
            ['core.norg.concealer'] = {},
            ['core.norg.dirman'] = {
              config = {
                workspaces = {
                  notes = '<path>',
                },
              },
            },
          },
        }
      end,

```
1. Open a lua file in nvim, I use my dotfiles 🤷🏿‍♂️ 
2. Enter command `:Neorg<CR>` sometimes this will open my neorg index file in my notes workspace, sometimes it won't 🤔 
3. If it works 😅 you should be in your `index.norg`.
4. Close buffer with `:bd`
5. Check ft for previous buffer which is now `norg`

**Comment by vhyrro** [comment]
Woah, that's like insanely buggy. Huh. I've had issues with Neorg randomly launching as i exit neovim which is hella weird too lol. I think I've managed to fix that issue though. The only issue i could think of is swap files, i recall having such a bug only once where the file would be opened twice and it'd error out. It could be because the workspace is set twice at boot. I'll try and fix this asap when i get home. As for the random filetype stuff I'll do some testing too

**Comment by vhyrro** [comment]
Yeah, it seems to have been duplicate code execution. From my current tests all seems to work fine now including the filetype stuff, could you double check when you have the time?

**Comment by vhyrro** [comment]
Ah, of course it is. Yeah for some reason I'm manually setting the filetype before launching the core, idk what I thought that was gonna do. I'm gonna remove it, gonna push it and hope that the problem goes away lol

**Comment by vhyrro** [comment]
What's odd to me is I can't reproduce it at all (even with the setup you mentioned which is very similar to mine anyway). Most of these fixes are practically shots in the dark hah

**Comment by akinsho** [comment]
That seems to have fixed it 👍🏿 tbh it's with my full config so I guess my minimal reproduction might have some stuff in it that was triggering this. It's also inside of a vim session so maybe some option got saved 🤷🏿 anyway it seems to be resolved now, thanks.

**Comment by vhyrro** [comment]
Glad to hear that, hopefully 13 other bugs don't randomly arise because of the changes lol
