### ISSUE TITLE
Will neorg support exporting to another filetypes ? e.g latex, pdf, markdown... 

### ISSUE THREAD

**Issue by rafamadriz** [vhyrro/neorg#4]
##### First, I'm just talking about the things I believe are awesome.
Hey, I've been following this project for a while now, it looks awesome. I've read the specification and there's a few things that I think were just excellent decisions in the design of this. I love how clean the syntax looks (personally I don't have any problem with markdown but this definitely looks better and makes more sense). And the other thing that I love is that this is being created within the context of being use with vim bindings. An example of this is the ordered lists, that fact you're using just tags to enclose ordered lists makes it so people can just `dd` an line an change the position without having to worry about the number (this is a pain in markdown), when I was reading the specification I thought that was such an elegant solution considering that is being made to be use in neovim. 

Now the real question of this issue, I didn't see any mention of exporting to other filetypes like with org mode. I think that one of the key features of org is being able to export to html, pdf, latex... and more. I suppose that if you're thinking if making this a better alternative to org, the export feature is planned. But I was wondering when you think this will be possible. (or mybe it already is, idk)

**Comment by molleweide** [comment]
I was just about to ask the same thing :D This project seems super cool. I have yet to try it tho since I found out about it this morning.

**Comment by vhyrro** [comment]
Wow, thanks a bunch for the kind words! What a way to make my day. Of course we're planning on supporting exporting, although it's currently planned for 0.2, not 0.1 - 0.1 is just supposed to be the initial release, the first stable up and running thing. The dream is to have an engine for pandoc, that way it will integrate very nicely and add support for converting to a tonne of different formats. There's also the plan to add a custom live HTML previewer which will run in the browser as an optional module that you can load. Additionally we're planning on adding an in-house solution that will automatically upgrade .org files to .norg files whenever an org file is detected, and conversion of directories filled with org files to Neorg workspaces. So yeah, big plans.

Hope that clears things up!

**Comment by molleweide** [comment]
> Wow, thanks a bunch for the kind words! What a way to make my day. Of course we're planning on supporting exporting, although it's currently planned for 0.2, not 0.1 - 0.1 is just supposed to be the initial release, the first stable up and running thing. The dream is to have an engine for pandoc, that way it will integrate very nicely and add support for converting to a tonne of different formats. There's also the plan to add a custom live HTML previewer which will run in the browser as an optional module that you can load. Additionally we're planning on adding an in-house solution that will automatically upgrade .org files to .norg files whenever an org file is detected, and conversion of directories filled with org files to Neorg workspaces. So yeah, big plans.
> 
> Hope that clears things up!

goosebumps!! holy shit dude

**Comment by rafamadriz** [comment]
> Wow, thanks a bunch for the kind words! What a way to make my day. Of course we're planning on supporting exporting, although it's currently planned for 0.2, not 0.1 - 0.1 is just supposed to be the initial release, the first stable up and running thing. The dream is to have an engine for pandoc, that way it will integrate very nicely and add support for converting to a tonne of different formats. There's also the plan to add a custom live HTML previewer which will run in the browser as an optional module that you can load. Additionally we're planning on adding an in-house solution that will automatically upgrade .org files to .norg files whenever an org file is detected, and conversion of directories filled with org files to Neorg workspaces. So yeah, big plans.
> 
> Hope that clears things up!

Okay thanks, that looks awesome. The integration with pandoc would be a game changer.

**Comment by NightMachinary** [comment]
@vhyrro Can you create an issue for the pandoc support, so that we can get notified about it?
