### ISSUE TITLE
Use vim's syntax conceal to conceal links

### ISSUE THREAD

**Issue by akinsho** [vhyrro/neorg#40]
I've observed that neorg's link syntax does not get concealed, which could be on purpose.
<img width="463" alt="Screen Shot 2021-07-29 at 15 45 41" src="https://user-images.githubusercontent.com/22454918/127513065-ca7ad95f-f932-4066-81c4-4eb35ad691f1.png">

I think though that this is a good use case for vim's built in conceal (as opposed to extmarks) because all the edge cases are handled already, a user can set their conceal cursor which controls the visibility of the concealed text so it is easy to edit. Lastly if transforming the existing text rather than replacing it then it is able to maintain normal highlights.

![syntax-conceal](https://user-images.githubusercontent.com/22454918/127512553-7da113d7-3e9a-48d5-b264-c5a909ea7c80.gif)

There is no good way to do this from lua and frankly I don't believe it is worth it to try till there is an API for it but in vimscript you could do something like what `vim-markdown` does.

https://github.com/plasticboy/vim-markdown/blob/8e5d86f7b85234d3d1b4207dceebc43a768ed5d4/syntax/markdown.vim#L66

**Comment by vhyrro** [comment]
Sounds like a great idea. Would definitely give Neorg a bit more of a professional feel. Thanks for the vim-markdown link, I'll make some tweaks to it to account for some extras the norg format provides and it should be good

**Comment by vhyrro** [comment]
I implemented this in the latest commit, mind checking it out and giving thoughts? It should work as expected (fingers crossed).

**Comment by mrossinek** [comment]
In theory it seems to work but it may be a good idea for Neorg to automatically set a higher `conceallevel`. Personally, I don't change that as part of my config so it stays at 0 where the concealing is not happening

**Comment by vhyrro** [comment]
We could add a configuration option to automatically set the conceallevel for norg buffers only. I can do that tomorrow. I don't know about modifying Neovim configuration variables but i suppose it shouldn't be awful in this context, right?

**Comment by mrossinek** [comment]
Well you could change it for the buffer only with `:setlocal`. I would have to look up what the lua-equivalent of that is.. :thinking:

**Comment by vhyrro** [comment]
Yeah, I'm aware you can do that (vim.opt_local btw) but i heard it's generally bad practice to do so. Shouldn't be bad in this scenario though I don't think

**Comment by mrossinek** [comment]
I did a little bit more thinking and I believe you may be right about not overwriting this setting in the general case. However, we should probably document that `conceallevel=2` should be set by the user. Obviously, a user can use a `FileType` or `BufEnter *.norg` autocommand (or even use a `.config/nvim/after/ftplugin/norg.vim/lua` file) to limit this setting to the norg filetype.

The reason I came to this conclusion is that similar writing plugins like [vim-markdown](https://github.com/plasticboy/vim-markdown/blob/8e5d86f7b85234d3d1b4207dceebc43a768ed5d4/doc/vim-markdown.txt#L246-L249) and [vimtex](https://github.com/lervag/vimtex/blob/830659752b8914f6b4567a00448901246e4d1841/doc/vimtex.txt#L4187-L4188) also require the user to apply this setting.

**Comment by vhyrro** [comment]
We could maybe provide a small warning message? I mean, it would detect the conceallevel and if it's 0 tell the user "Hey, to get nice conceals you may be interested in setting the conceallevel to `2`. Set `conceal_level_acknowledge = true` in the module's configuration to remove this message". What about that?

**Comment by akinsho** [comment]
@vhyrro just tried this out, and it works nicely 👍🏿 thanks for adding it. Regarding the conceallevel I definitely think neorg should not mess with it. It's a window option, so if a user switched buffer but kept the same window, you'd have messed up their settings for some other buffer.

I think it's up to the user to decide how/if they want concealing and not plugins to tweak them. As you say though, it's probably worth documenting the conceal behaviour or building something in to tell people. I personally think docs should be enough rather than stuff printing out which can be annoying.

**Comment by vhyrro** [comment]
Glad to hear all works nicely. I'll probably just mention it in an easily accessible place in the docs so people don't miss it - maybe even in the README 👍
