### ISSUE TITLE
[BUG] Bad argument #3 to 'fs_write' (number expected, got no value)

### ISSUE THREAD

**Issue by vuki656** [vhyrro/neorg#44]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

NVIM v0.6.0-dev+8-g75f758b99

### Log Output

**I think those errors are from when I was trying to run some neorg commands and are likely not related to the actual bug but regardless, maybe it is connected somehow.** 

`[ERROR petak, 30. srpnja 2021. 18:23:12 CEST] ...r/start/neorg/lua/neorg/modules/core/neorgcmd/module.lua:295: Unable to execute neorg command under name set-mode - minimum argument count not satisfied. The command requires at least 1 arguments.`

`[ERROR petak, 30. srpnja 2021. 18:24:07 CEST] ...r/start/neorg/lua/neorg/modules/core/neorgcmd/module.lua:295: Unable to execute neorg command under name core.keybinds.trigger - minimum argument count not satisfied. The command requires at least 2 arguments.`

`[ERROR petak, 30. srpnja 2021. 20:33:11 CEST] ...r/start/neorg/lua/neorg/modules/core/neorgcmd/module.lua:295: Unable to execute neorg command under name nil - minimum argument count not satisfied. The command requires at least 1 arguments.`

`[ERROR petak, 30. srpnja 2021. 20:33:15 CEST] ...r/start/neorg/lua/neorg/modules/core/neorgcmd/module.lua:295: Unable to execute neorg command under name module.load - minimum argument count not satisfied. The command requires at least 1 arguments.`

### Branch

unstable

### Loaded modules

```lua
neorg.setup({
    load = {
        ["core.defaults"] = {},
        ["core.norg.concealer"] = {},
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    my_workspace = "~/notes",
                },
            },
        },
        ["core.keybinds"] = {
            config = {
                default_keybinds = true,
                neorg_leader = "<Leader>o",
            },
        },
    },
})
```

### Expected behavior

When I close a `norg` file, for it to not error out.

### Actual behavior

When I close a `norg` file I get the following error.

I'm closing it with `:qa`

```
Error executing luv callback:
...tart/neorg/lua/neorg/modules/core/norg/dirman/module.lua:371: bad argument #3 to 'fs_write' (number expected, got no value)
```

### Other information

This happens regardless if there is content in the file or not.
### Help

No

**Comment by vhyrro** [comment]
Hm, that's rather weird. Taking a look at the libuv docs, I get this:
![weird](https://user-images.githubusercontent.com/76052559/127735970-be0e7a1c-772a-481b-a4af-facf3cb25597.png)
It allows this value to be set to `nil` so I don't see why that error would arise in any case. Could it be because of the nvim version by any chance? This is my version:
`NVIM v0.6.0-dev+91-gd628e4250`

It seems to be fairly ahead of yours. I don't know how libuv gets bundled with neovim exactly but it's the only logical solution I could come to.

I'll provide the third argument to fs_write just in case someone running an older version of neovim/libuv encounters this bug again :)

**Comment by vhyrro** [comment]
I just pushed a commit into `unstable`, I hope that fixes the issue. Please update and check whether all's good :)

**Comment by vuki656** [comment]
Yup, fixed. Thanks :heart:
