### ISSUE TITLE
[BUG] Parts of a text link concealed 

### ISSUE THREAD

**Issue by vuki656** [vhyrro/neorg#49]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

NVIM v0.6.0-dev+8-g75f758b99

### Log Output

N/A

### Branch

unstable

### Loaded modules
```lua
neorg.setup({
    load = {
        ["core.defaults"] = {},
        ["core.norg.concealer"] = {},
        ["core.norg.dirman"] = {
            config = {
                workspaces = {
                    my_workspace = "~/notes",
                },
            },
        },
        ["core.keybinds"] = {
            config = {
                default_keybinds = true,
                neorg_leader = "<Leader>o",
            },
        },
    },
})
```

### Expected behavior

When I paste a plain text link for it no to be concealed and all characters to be visible.

### Actual behavior

![image](https://user-images.githubusercontent.com/8104698/127752327-8ec7c68c-6d0d-4b7a-8238-1f018f96f19e.png)

The plain text of it is: https://neovim.discourse.group/
But its displaying it as in the picture 

### Help

No

**Comment by vhyrro** [comment]
I'm pretty sure I've fixed this now in the commit I released, check it out when you can plz!

**Comment by vuki656** [comment]
Looking good!
