### ISSUE TITLE
off topic maybe but which software are u using for music making lol?

### ISSUE THREAD

**Issue by molleweide** [vhyrro/neorg#5]
Yo, 

I read you like to make music so I just wanted to know which daw you fancy mate???

**Comment by vhyrro** [comment]
Uh, I feel like I'm about to start a flame war with this comment, so Imma close this thread ASAP :P

As cursed as it sounds, I'm the non-based proprietary ableton user running in a QEMU Windows VM with passthrough

**Comment by molleweide** [comment]
Haha yeah i was assuming you’d use like reaper where you can use lua scripting?
