### ISSUE TITLE
[DOCS] Add example.norg 

### ISSUE THREAD

**Issue by vuki656** [vhyrro/neorg#52]
Opening this in reference to #14 

@vhyrro would this include everything from the spec? 

If so, I could send a PR

**Comment by vhyrro** [comment]
The EXAMPLE.norg file would indeed contain pretty much the entire spec so people can just get accustomed to the format without needing to read a bunch of technical jargon. The small problem is that there were certain changes that were made that I've yet to document, e.g. changing `_this_` to underline and making `/this/` mean italic instead. I don't vividly remember whether I've made any other big changes

**Comment by molleweide** [comment]
> The small problem is that there were certain changes that were made that I've yet to document, e.g. changing `_this_` to underline and making `/this/` mean italic instead. I don't vividly remember whether I've made any other big changes

Just let it evolve and things will probably be fine right? This is gonna be awesome.

**Comment by vhyrro** [comment]
Yeah, sure thing! The EXAMPLE.norg can be made entirely with the old spec and then can be updated incrementally
