### ISSUE TITLE
[BUG]  Can't get Neorg working

### ISSUE THREAD

**Issue by beauwilliams** [vhyrro/neorg#58]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

0.5 release version

### Log Output

There is no log output or log file

### Branch

master

### Loaded modules

["core.defaults"]
["core.norg.concealer"]
["core.norg.dirman"] 

### Expected behavior

You can use the :Neorg command etc

### Actual behavior

There is no :Neorg command or any other aspect of the plugin loaded.
The neorg git repo is cloned and sitting on my machine by packer correctly.
I can produce an error if I rm the git repo, so it is definitely being loaded by packercompiled.vim

### Other information

I used the code snippet in readme to set up Neorg, I also tried loading it in my init.lua and init.vim but still could not get it working 

### Help

No

**Comment by vuki656** [comment]
Could you post a code snippet of how you initialized the plugin?

**Comment by beauwilliams** [comment]
> Could you post a code snippet of how you initialized the plugin?

Sure happy to share it here. It's pretty much the readme snippet except updated workspace path

```lua
        use {
            "vhyrro/neorg",
            config = function()
                require('neorg').setup {
                    -- Tell Neorg what modules to load
                    load = {
                        ["core.defaults"] = {}, -- Load all the default modules
                        ["core.norg.concealer"] = {}, -- Allows for use of icons
                        ["core.norg.dirman"] = { -- Manage your directories with Neorg
                            config = {
                                workspaces = {
                                    my_workspace = "~/Dropbox/Software Eng/Workspaces/Neorg"
                                }
                            }
                        }
                    },
                }
            end,
            requires = "nvim-lua/plenary.nvim"
        }

```

**Comment by vuki656** [comment]
You mentioned that you cloned the plugin but in the snippet, you are referencing `vhyrro/neorg` in `packer` use which will get it from Github. Shouldn't it point to the local path then?

**Comment by vhyrro** [comment]
I think the issue could be that on the master branch neorg only launches when entering a .norg file. Using the unstable branch should fix this problem. :Neorg would then kickstart the core and you would gain access to all functionality.

Sorry about the weird discrepancies between unstable and main, this will not be the case before 0.1 releases, everything is in a bit of a mess right now :)

**Comment by vuki656** [comment]
> I think the issue could be that on the master branch neorg only launches when entering a .norg file. Using the unstable branch should fix this problem. :Neorg would then kickstart the core and you would gain access to all functionality.
> 
> Sorry about the weird discrepancies between unstable and main, this will not be the case before 0.1 releases, everything is in a bit of a mess right now :)

Just got weirded out when I switched to `master`, and couldn't run `:Neorg` :smile:. Maybe it should be noted in the docs?

**Comment by vhyrro** [comment]
That sounds like a good idea yeah, I'll take care of that tomorrow

**Comment by beauwilliams** [comment]
> You mentioned that you cloned the plugin but in the snippet, you are referencing `vhyrro/neorg` in `packer` use which will get it from Github. Shouldn't it point to the local path then?

Yes packer clones it for me, but I went into the /start dir where packer keeps git repos and removed it manually :)

**Comment by beauwilliams** [comment]
> I think the issue could be that on the master branch neorg only launches when entering a .norg file. Using the unstable branch should fix this problem. :Neorg would then kickstart the core and you would gain access to all functionality.
> 
> Sorry about the weird discrepancies between unstable and main, this will not be the case before 0.1 releases, everything is in a bit of a mess right now :)

Aha. Yes that fixed it. I knew it had to be something simple. Thanks!
