### ISSUE TITLE
[BUG] `vim.opt_local` is nil

### ISSUE THREAD

**Issue by mheden** [vhyrro/neorg#66]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

NVIM v0.5.0-dev+1357-g192f89ea1 (on Win10)

### Log Output

No such file available

### Branch

master

### Loaded modules

```
lua << EOF
    require('neorg').setup {
        -- Tell Neorg what modules to load
        load = {
            ["core.defaults"] = {}, -- Load all the default modules
            ["core.norg.concealer"] = {}, -- Allows for use of icons
            ["core.norg.dirman"] = { -- Manage your directories with Neorg
               config = {
                    workspaces = {
                        my_workspace = "~/neorg"
                    }
                }
            }
       },
    }
```

### Expected behavior

No errors when opening an norg file.

### Actual behavior

When opening an norg file (`:e c:\tmp\foo.norg`) I get the following error:
![image](https://user-images.githubusercontent.com/8748209/129705673-6929227c-a165-4e06-9ea1-4d2729764edf.png)

It seems like `vim.opt_local` is nil for some reason. As far as I can tell from the neovim documentaiton, it should be available so maybe this issue should go there instead?

### Help

No

**Comment by vhyrro** [comment]
From what I can see you might be running a Neovim version that doesn't have `vim.opt_local` supported yet? I'd try updating/recompiling nvim to either the 0.5 release (it seems you're running a dev build that might have been compiled at an earlier point in time) or to the absolute latest version :)

**Comment by mheden** [comment]
I was running a nightly build version which was fairly new but I updated to the very latest and now it is working. Sorry for the inconvenience!
