### ISSUE TITLE
[BUG] Can't integrate with lazy-loaded nvim-compe

### ISSUE THREAD

**Issue by glyh** [vhyrro/neorg#68]
### Contributions

- [X] I have read [contribution guidelines](https://github.com/vhyrro/neorg/blob/main/docs/CONTRIBUTING.md)

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the latest neovim version (0.5)

### Neovim Version

NVIM v0.6.0-dev+98-ga5c25e4f3

### Log Output

No such file

### Branch

master

### Loaded modules

```lua
      require("neorg").setup({
        load = {
          ["core.defaults"] = {}, -- Load all the default modules
          ["core.norg.concealer"] = {}, -- Allows for use of icons
          ["core.norg.dirman"] = { -- Manage your directories with Neorg
            config = {
              workspaces = {
                my_workspace = "~/neorg"
              }
            }
          }
        }
      })
```

### Expected behavior

neorg have some kind of fallbacks for lazy loaded nvim-compe, here's the configuration for packer.nvim:
```lua
  use {"hrsh7th/nvim-compe",
    event = "InsertEnter",
    config = function()
      require'compe'.setup {
        enabled = true;
        autocomplete = true;
        debug = false;
        min_length = 1;
        preselect = 'enable';
        throttle_time = 80;
        source_timeout = 200;
        resolve_timeout = 800;
        incomplete_delay = 400;
        max_abbr_width = 100;
        max_kind_width = 100;
        max_menu_width = 100;
        documentation = {
          border = { '', '' ,'', ' ', '', '', '', ' ' },
          winhighlight = "NormalFloat:CompeDocumentation,FloatBorder:CompeDocumentationBorder",
          max_width = 120,
          min_width = 60,
          max_height = math.floor(vim.o.lines * 0.3),
          min_height = 1,
        };
```

### Actual behavior

packer.nvim: Error running config for neorg: ...ua/neorg/modules/core/integrations/nvim-compe/module.lua:22: nvim-compe not found, aborting...

### Potentially conflicting plugins

nvim-compe, packer.nvim

### Other information

None. 

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

### Implementation help

Can you provide a clear structure of the project and where is the related scripts?

**Comment by vhyrro** [comment]
Hmm, this is an interesting bug since i don't think there's much neorg itself can do. We can't just set a callback and wait until nvim-compe loads :P

I think your best bet is to disable the completion module in the `load` table (check the wiki entry on metamodules if you want to disable individual modules from core.defaults) and then load it after you've called the nvim-compe setup using `neorg.modules.load_module("core.norg.completion")`. That should prevent the error from occurring since compe will be loaded by then.

What i *can* do though is make the error a bit less annoying and fatal :). If you have any extra questions feel free to ask!

**Comment by glyh** [comment]
Thanks, here's the workaround: 
```lua
  use {"vhyrro/neorg",
    ft = "norg",
    config = function()
      require("neorg").setup({
        load = {
          ["core.defaults"] = {
            config = {
              disable = { "core.norg.completion" }
            }
          }, 
          -- ......        
        }
      })
    end,
    requires = "nvim-lua/plenary.nvim"
  }
use {"hrsh7th/nvim-compe",
    event = "InsertEnter",
    config = function()
      require'compe'.setup {
        -- ......
      }
      if vim.bo.filetype == "norg" then
        require("neorg").modules.load_module("core.norg.completion")
      end
    end
  }
```

**Comment by vhyrro** [comment]
Glad to hear that it worked! :)

I'll go ahead and make the compe errors less annoying and in-your-face tomorrow since it's rather late today.
